import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { Toaster } from "@/components/ui/toaster";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Issue tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${figtree.className} bg-slate-50`}>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
